import { VerticalBox, HorizontalBox, Palette } from "std-widgets.slint";
import { TicketStr, IdCopy } from "../common.slint";

export component TicketCard inherits Rectangle {
    in property <TicketStr> ticket;
    in property <string> from_queue_id;

    // Callbacks
    callback start_dragging(string, string, length, length);
    callback move_dragging(length, length);
    callback drop_ticket(length);
    callback delete_clicked(TicketStr);
    callback edit_clicked(TicketStr);

    border-radius: 8px;
    border-width: 1px;
    height: 140px;
    drop-shadow-blur: touch-area.has-hover ? 8px : 2px;
    drop-shadow-offset-y: touch-area.has-hover ? 4px : 1px;
    drop-shadow-color: #00000020;
    animate background, border-color, drop-shadow-blur, drop-shadow-offset-y { duration: 150ms; }

    touch-area := TouchArea {
        pointer-event(event) => {
            if (event.button == PointerEventButton.left && event.kind == PointerEventKind.down) {
                start_dragging(ticket.id, from_queue_id, self.absolute-position.x + self.mouse-x, self.absolute-position.y + self.mouse-y);
            }
            if (event.kind == PointerEventKind.up) {
                drop_ticket(self.absolute-position.x + self.mouse-x);
            }
        }
        moved => {
            if (self.pressed) {
                move_dragging(self.absolute-position.x + self.mouse-x, self.absolute-position.y + self.mouse-y);
            }
        }
        clicked => {
            edit_clicked(ticket);
        }
    }

    VerticalBox {
        padding: 12px;
        spacing: 8px;

        HorizontalBox {
            padding: 0px;
            alignment: space-between;

            Text {
                text: ticket.title;
                font-weight: 700;
                font-size: 15px;
                overflow: elide;
            }

            Rectangle {
                width: 24px;
                height: 24px;
                background: touch-del.pressed ? #eb1abaff : (touch-del.has-hover ? #ff0048ff : transparent);
                border-radius: 4px;

                Text {
                    text: "×";
                    font-size: 18px;
                    horizontal-alignment: center;
                    vertical-alignment: center;
                }

                touch-del := TouchArea {
                    clicked => {
                        delete_clicked(ticket);
                    }
                }
            }
        }

        Text {
            text: ticket.snippet;
            font-size: 13px;
            wrap: no-wrap;
            overflow: elide;
        }

        HorizontalLayout {
            spacing: 8px;
            alignment: space-between;
            VerticalLayout {
                spacing: 2px;
                alignment: start;
                IdCopy {
                    id: ticket.id;
                    font-size: 11px;
                }

                if ticket.author != "": Text {
                    text: "✍ " + ticket.author;
                    font-size: 11px;
                    font-weight: 500;
                    color: #d33682; // A nice magenta/berry color
                }

                if ticket.assigned_to != "": Text {
                    text: "👤 " + ticket.assigned_to;
                    font-size: 11px;
                    font-weight: 500;
                    color: Palette.accent-background;
                }
            }

            VerticalLayout {
                spacing: 2px;
                Text {
                    text: "C: " + ticket.created_at;
                    font-size: 9px;
                }

                Text {
                    text: "U: " + ticket.updated_at;
                    font-size: 9px;
                }
            }
        }
    }
}
