import { Button, VerticalBox, Palette } from "std-widgets.slint";
import { CloseButton } from "../common.slint";

export component SearchHistoryMenu inherits Rectangle {
    in property <[string]> history;
    callback select-history-item(string);
    callback remove-history-item(string);
    callback close();

    background: Palette.background;
    border-radius: 8px;
    border-width: 1px;
    border-color: Palette.border;
    drop-shadow-blur: 15px;
    drop-shadow-color: #00000040;

    height: self.preferred-height;

    VerticalBox {
        padding: 16px;
        spacing: 12px;

        Text {
            text: "Recent Searches";
            font-size: 16px;
            font-weight: 700;
        }

        VerticalLayout {
            spacing: 4px;
            for item[index] in history: Rectangle {
                height: 32px;
                background: touch.has-hover ? Palette.alternate-background : transparent;
                border-radius: 4px;

                touch := TouchArea {
                    clicked => {
                        select-history-item(item);
                    }
                }

                HorizontalLayout {
                    padding-left: 12px;
                    padding-right: 8px;
                    spacing: 8px;

                    Text {
                        text: item;
                        vertical-alignment: center;
                        font-size: 14px;
                        overflow: elide;
                        horizontal-stretch: 1;
                    }

                    CloseButton {
                        size: 20px;
                        vertical-stretch: 0;
                        horizontal-stretch: 0;
                        clicked => {
                            remove-history-item(item);
                        }
                    }
                }
            }
        }

        if (history.length == 0): Text {
            text: "No history yet";
            font-italic: true;
            opacity: 0.5;
        }

        HorizontalLayout {
            alignment: end;
            close-btn := Button {
                text: "Close";
                clicked => {
                    close();
                }
            }
        }
    }
}
