import {
    Button,
    LineEdit,
    TextEdit,
    ComboBox,
    VerticalBox,
    HorizontalBox,
    Palette,
} from "std-widgets.slint";
import { IdCopy, CloseButton, ModalBackdrop, Theme, TicketStr } from "../common.slint";
export component TicketEdit inherits Rectangle {
    in-out property <TicketStr> ticket;
    in property <[string]> users;

    callback save(string, string, string, string, int); // id, title, desc, assigned_to, points
    callback cancel();
    callback attach-file(string) -> string;

    ModalBackdrop {
        dismiss => {
            cancel();
        }

        Rectangle {
            width: 100%;
            height: 100%;
            background: Palette.background;

            TouchArea { }

            VerticalBox {
                padding: 40px;
                spacing: 24px;

                HorizontalLayout {
                    padding: 0px;
                    alignment: space-between;

                    cancel-btn := Button {
                        text: @tr("Cancel");
                        width: 100px;
                        height: 40px;
                        clicked => {
                            cancel();
                        }
                    }

                    HorizontalLayout {
                        alignment: center;
                        spacing: 8px;
                        Text {
                            text: ticket.id == "" ? @tr("Create New Ticket") : @tr("Edit Ticket ");
                            font-size: 32px;
                            font-weight: 800;
                            overflow: elide;
                        }

                        if ticket.id != "": IdCopy {
                            id: ticket.id;
                            font-size: 32px;
                            height: 48px; // Match line height of the text roughly
                    }
                    }

                    save-btn := Button {
                        text: @tr("Save Ticket");
                        primary: true;
                        width: 120px;
                        height: 40px;
                        clicked => {
                            save(ticket.id, ticket.title, ticket.description, ticket.assigned_to, ticket.points);
                        }
                    }
                }

                HorizontalLayout {
                    spacing: 24px;
                    alignment: start;
                    if ticket.author != "": VerticalLayout {
                        spacing: 8px;
                        Text {
                            text: @tr("Author");
                            overflow: elide;
                            font-size: 11px;
                            font-weight: 800;
                            opacity: 0.6;
                        }

                        Text {
                            text: ticket.author;
                            font-size: 14px;
                            height: 40px;
                            vertical-alignment: center;
                            color: Theme.author-color;
                            overflow: elide;
                        }
                    }

                    VerticalLayout {
                        spacing: 8px;
                        Text {
                            text: @tr("Assigned To");
                            overflow: elide;
                            font-size: 11px;
                            font-weight: 800;
                            opacity: 0.6;
                        }

                        HorizontalLayout {
                            spacing: 8px;
                            assign-combo := ComboBox {
                                model: users;
                                current-value: ticket.assigned_to == "" ? @tr("<unassigned>") : ticket.assigned_to;
                                height: 40px;
                                width: 200px;
                                selected(val) => {
                                    ticket.assigned_to = (val == "<unassigned>") ? "" : val;
                                }
                            }

                            if ticket.assigned_to != "": CloseButton {
                                size: 32px;
                                clicked => {
                                    ticket.assigned_to = "";
                                }
                            }
                        }
                    }

                    VerticalLayout {
                        spacing: 8px;
                        Text {
                            text: @tr("Points");
                            overflow: elide;
                            font-size: 11px;
                            font-weight: 800;
                            opacity: 0.6;
                        }

                        ComboBox {
                            model: ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10"];
                            current-value: ticket.points + "";
                            height: 40px;
                            width: 80px;
                            selected(val) => {
                                if (val == "0") {
                                    ticket.points = 0;
                                } else if (val == "1") {
                                    ticket.points = 1;
                                } else if (val == "2") {
                                    ticket.points = 2;
                                } else if (val == "3") {
                                    ticket.points = 3;
                                } else if (val == "4") {
                                    ticket.points = 4;
                                } else if (val == "5") {
                                    ticket.points = 5;
                                } else if (val == "6") {
                                    ticket.points = 6;
                                } else if (val == "7") {
                                    ticket.points = 7;
                                } else if (val == "8") {
                                    ticket.points = 8;
                                } else if (val == "9") {
                                    ticket.points = 9;
                                } else if (val == "10") {
                                    ticket.points = 10;
                                }
                            }
                        }
                    }
                }

                VerticalLayout {
                    spacing: 8px;
                    Text {
                        text: @tr("Title");
                        overflow: elide;
                        font-size: 11px;
                        font-weight: 800;
                        opacity: 0.6;
                    }

                    title-input := LineEdit {
                        text <=> ticket.title;
                        placeholder-text: @tr("What needs to be done?");
                        height: 40px;
                    }
                }

                VerticalLayout {
                    spacing: 8px;
                    Text {
                        text: @tr("Description");
                        overflow: elide;
                        font-size: 11px;
                        font-weight: 800;
                        opacity: 0.6;
                    }

                    desc-input := TextEdit {
                        text <=> ticket.description;
                        placeholder-text: @tr("What needs to be done?");
                        preferred-height: 400px;
                        vertical-stretch: 1;
                    }

                    if ticket.id != "": HorizontalLayout {
                        alignment: end;
                        attach-btn := Button {
                            text: @tr("Attach File");
                            height: 40px;
                            clicked => {
                                let link = root.attach-file(ticket.id);
                                if link != "" {
                                    if ticket.description != "" {
                                        ticket.description += "\n\n" + link;
                                    } else {
                                        ticket.description = link;
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
